# Generated by Django 4.1.7 on 2023-03-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0002_alter_visitor_email_alter_visitor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=2)),
                ('number', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('given', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('canceled', models.BooleanField()),
                ('minutes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'отсутствует'), (1, 'фитнес'), (2, 'аэробика'), (3, 'стрейчинг'), (4, 'пилатес'), (5, 'батуты'), (6, 'бассейн'), (7, 'тренажерный зал'), (8, 'йога')], default=(0, 'отсутствует'))),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(unique=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='sportcenterapp.passport')),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='session',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='sportcenterapp.session'),
            preserve_default=False,
        ),
    ]
