# Generated by Django 4.1.7 on 2023-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0003_passport_session_instructor_visitor_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.IntegerField(choices=[(1, 'фитнес'), (2, 'аэробика'), (3, 'стрейчинг'), (4, 'пилатес'), (5, 'батуты'), (6, 'бассейн'), (7, 'тренажерный зал'), (8, 'йога')]),
        ),
    ]
