# Generated by Django 4.1.7 on 2023-03-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0004_alter_session_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Coach',
        ),
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='sportcenterapp.coach'),
            preserve_default=False,
        ),
    ]
