# Generated by Django 4.1.7 on 2023-03-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0005_rename_instructor_coach_session_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='sportcenterapp.coach'),
        ),
    ]
