# Generated by Django 4.1.7 on 2023-03-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0008_alter_session_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='passport',
        ),
    ]
