# Generated by Django 4.1.7 on 2023-03-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0009_remove_coach_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='sportcenterapp.coach'),
        ),
    ]
