# Generated by Django 4.1.7 on 2023-04-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0011_alter_session_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='passport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='sportcenterapp.passport'),
            preserve_default=False,
        ),
    ]
