# Generated by Django 4.1.7 on 2023-04-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0012_coach_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='session',
        ),
        migrations.CreateModel(
            name='VisitorToSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='sportcenterapp.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='sportcenterapp.visitor')),
            ],
        ),
    ]
