# Generated by Django 4.1.7 on 2023-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0013_remove_visitor_session_visitortosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='id',
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
