# Generated by Django 4.1.7 on 2023-04-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0014_remove_passport_id_alter_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='sportcenterapp.passport', unique=True),
        ),
    ]
