# Generated by Django 4.1.7 on 2023-04-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0015_alter_coach_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortosession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='sportcenterapp.session', unique=True),
        ),
    ]
