# Generated by Django 4.1.7 on 2023-04-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0016_alter_visitortosession_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='passport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='sportcenterapp.passport'),
        ),
        migrations.AlterField(
            model_name='visitortosession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='sportcenterapp.session'),
        ),
    ]
