# Generated by Django 4.1.7 on 2023-04-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='visitors',
            new_name='visitor',
        ),
    ]
