# Generated by Django 4.1.7 on 2023-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0002_alter_subscription_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='visitor',
        ),
        migrations.AddField(
            model_name='subscription',
            name='visitor',
            field=models.ManyToManyField(related_name='subscriptions', to='sportcenterapp.visitor'),
        ),
    ]
