# Generated by Django 4.1.7 on 2023-05-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcenterapp', '0003_remove_subscription_visitor_subscription_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='people',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='visits',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
